package: llm_algo_search.algorithms.compress_clm
proposal_history_filename: proposal_history_compress_clm.pkl

model_name: gpt2-large
hidden_dim_name: n_embd
attention_head_name: n_head
small_hidden_dims: 256
small_attention_heads: 8

dataset_name: Salesforce/wikitext
dataset_config_name: wikitext-103-raw-v1
block_size: 1024
take_head: 30
batch_size: 1
gradient_accumulation_steps: 8
num_epochs: 0.1
lr: 2e-4
output_dir: outputs
preprocessing_num_workers: 4
save_strategy: 'no'
lr_scheduler_type: constant

max_step_time: 2.0