package: llm_algo_search.algorithms.distill_clm
proposal_history_filename: proposal_history_distill_clm.pkl

model_name: gpt2
target_model_name: gpt2-large
dataset_name: Salesforce/wikitext
dataset_config_name: wikitext-103-raw-v1
block_size: 1024
take_head: null
batch_size: 4
gradient_accumulation_steps: 1
num_epochs: 1
lr: 2e-4
output_dir: outputs
preprocessing_num_workers: 4