package: llm_algo_search.algorithms.s2ef_rr
proposal_history_filename: proposal_history_s2ef_rr.pkl

all_model_dims: [128, 256, 512]
train_dataset_path: data/train/rattled-300-subsampled
val_dataset_path: data/val/rattled-300-subsampled
batch_size: 8
lr: 1e-3
num_epochs: 1
device: cpu
max_train_batches: null
max_eval_batches: null