trainer: ocp_qs

dataset:
  train:
    format: oc22_lmdb
    src: data/oc20+data/oc22/is2re-total/train
    train_on_oc20_total_energies: True
    # download at https://dl.fbaipublicfiles.com/opencatalystproject/data/oc22/oc20_ref.pkl
    oc20_ref: path/to/oc20_ref.pkl
    key_mapping:
      y_relaxed: energy
  val:
    src: data/oc22/is2re-total/val_id

logger: wandb

outputs:
  energy:
    shape: 1
    level: system

loss_functions:
  - energy:
      fn: quantile_huber
      coefficient: 1.
      kwargs:
        num_quantiles: 9

evaluation_metrics:
  metrics:
    energy:
      - mae
      - mse
      - energy_within_threshold
  primary_metric: energy_mae