package: llm_algo_search.tasks.rl_clm
proposal_history_filename: proposal_history_rl_clm.pkl

model_name: Qwen/Qwen2-0.5B-Instruct
dataset_name: trl-lib/tldr
dataset_config_name: null
take_head: null

preprocessing_num_workers: 4
max_step_time: 0

train_args:
  per_device_train_batch_size: 1
  per_device_eval_batch_size: 1
  gradient_accumulation_steps: 1
  learning_rate: 1e-6
  output_dir: outputs
  overwrite_output_dir: true
  num_train_epochs: 0.1
  save_strategy: 'no'
  lr_scheduler_type: constant

  beta: 0.04
  use_vllm: false
  max_prompt_length: 512
  max_completion_length: 256
  num_generations: 8
  temperature: 0.9
  remove_unused_columns: false

peft_config:
  use_peft: false

