# @package _global_

defaults:
  - _self_
  - llm: anthropic

algo_package: llm_algo_search.algorithms.example
proposal_history_filename: proposal_history.pkl
load_existing: true
max_steps: 5
max_errors: 3
log_level: DEBUG